// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: correspondent.sql

package db

import (
	"context"
)

const createCorrespondent = `-- name: CreateCorrespondent :one

INSERT INTO correspondent (name)
VALUES ($1)
RETURNING id, name, created_at
`

// Correspondent CRUD.
// A person or entity whose documents/receipts are tracked.
func (q *Queries) CreateCorrespondent(ctx context.Context, name string) (Correspondent, error) {
	row := q.db.QueryRowContext(ctx, createCorrespondent, name)
	var i Correspondent
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteCorrespondent = `-- name: DeleteCorrespondent :exec
DELETE FROM correspondent
WHERE id = $1
`

func (q *Queries) DeleteCorrespondent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCorrespondent, id)
	return err
}

const getCorrespondent = `-- name: GetCorrespondent :one
SELECT id, name, created_at FROM correspondent
WHERE id = $1
`

func (q *Queries) GetCorrespondent(ctx context.Context, id int64) (Correspondent, error) {
	row := q.db.QueryRowContext(ctx, getCorrespondent, id)
	var i Correspondent
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getCorrespondentByName = `-- name: GetCorrespondentByName :one
SELECT id, name, created_at FROM correspondent
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetCorrespondentByName(ctx context.Context, name string) (Correspondent, error) {
	row := q.db.QueryRowContext(ctx, getCorrespondentByName, name)
	var i Correspondent
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listCorrespondents = `-- name: ListCorrespondents :many
SELECT id, name, created_at FROM correspondent
ORDER BY name
`

func (q *Queries) ListCorrespondents(ctx context.Context) ([]Correspondent, error) {
	rows, err := q.db.QueryContext(ctx, listCorrespondents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Correspondent{}
	for rows.Next() {
		var i Correspondent
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCorrespondent = `-- name: UpdateCorrespondent :one
UPDATE correspondent
SET name = $2
WHERE id = $1
RETURNING id, name, created_at
`

type UpdateCorrespondentParams struct {
	ID   int64
	Name string
}

func (q *Queries) UpdateCorrespondent(ctx context.Context, arg UpdateCorrespondentParams) (Correspondent, error) {
	row := q.db.QueryRowContext(ctx, updateCorrespondent, arg.ID, arg.Name)
	var i Correspondent
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
