// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: marketplace_link.sql

package db

import (
	"context"
)

const createMarketplaceLink = `-- name: CreateMarketplaceLink :one

INSERT INTO marketplace_link (product_a_id, product_b_id)
VALUES ($1, $2)
RETURNING id, product_a_id, product_b_id, created_at
`

type CreateMarketplaceLinkParams struct {
	ProductAID int64
	ProductBID int64
}

// Marketplace_link CRUD.
// A bidirectional pair link between two products across marketplaces.
func (q *Queries) CreateMarketplaceLink(ctx context.Context, arg CreateMarketplaceLinkParams) (MarketplaceLink, error) {
	row := q.db.QueryRowContext(ctx, createMarketplaceLink, arg.ProductAID, arg.ProductBID)
	var i MarketplaceLink
	err := row.Scan(
		&i.ID,
		&i.ProductAID,
		&i.ProductBID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMarketplaceLink = `-- name: DeleteMarketplaceLink :exec
DELETE FROM marketplace_link
WHERE id = $1
`

func (q *Queries) DeleteMarketplaceLink(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMarketplaceLink, id)
	return err
}

const getMarketplaceLink = `-- name: GetMarketplaceLink :one
SELECT id, product_a_id, product_b_id, created_at FROM marketplace_link
WHERE id = $1
`

func (q *Queries) GetMarketplaceLink(ctx context.Context, id int64) (MarketplaceLink, error) {
	row := q.db.QueryRowContext(ctx, getMarketplaceLink, id)
	var i MarketplaceLink
	err := row.Scan(
		&i.ID,
		&i.ProductAID,
		&i.ProductBID,
		&i.CreatedAt,
	)
	return i, err
}

const listMarketplaceLinks = `-- name: ListMarketplaceLinks :many
SELECT id, product_a_id, product_b_id, created_at FROM marketplace_link
ORDER BY id
`

func (q *Queries) ListMarketplaceLinks(ctx context.Context) ([]MarketplaceLink, error) {
	rows, err := q.db.QueryContext(ctx, listMarketplaceLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketplaceLink{}
	for rows.Next() {
		var i MarketplaceLink
		if err := rows.Scan(
			&i.ID,
			&i.ProductAID,
			&i.ProductBID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketplaceLinksByProduct = `-- name: ListMarketplaceLinksByProduct :many
SELECT id, product_a_id, product_b_id, created_at FROM marketplace_link
WHERE product_a_id = $1 OR product_b_id = $1
ORDER BY id
`

func (q *Queries) ListMarketplaceLinksByProduct(ctx context.Context, productAID int64) ([]MarketplaceLink, error) {
	rows, err := q.db.QueryContext(ctx, listMarketplaceLinksByProduct, productAID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketplaceLink{}
	for rows.Next() {
		var i MarketplaceLink
		if err := rows.Scan(
			&i.ID,
			&i.ProductAID,
			&i.ProductBID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
