// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

// A person or entity whose documents/receipts are tracked
type Correspondent struct {
	ID        int64
	Name      string
	CreatedAt time.Time
}

// Bidirectional link between two products across different marketplaces
type MarketplaceLink struct {
	ID int64
	// FK to product — lower ID side of the pair (enforced by CHECK)
	ProductAID int64
	// FK to product — higher ID side of the pair (enforced by CHECK)
	ProductBID int64
	CreatedAt  time.Time
}

// A price observation — one per raw item (1:1 relationship)
type PriceRecord struct {
	ID int64
	// FK to raw_item — UNIQUE enforces one price record per item
	RawItemID int64
	// Total price as printed on the receipt
	TotalPrice float64
	// Precomputed price per base_unit (populated by the ingestion pipeline)
	UnitPrice sql.NullFloat64
	Currency  string
	CreatedAt time.Time
}

// A canonical product after normalization
type Product struct {
	ID          int64
	DisplayName string
	// Normalized unit for price comparison (e.g., g, kg, ml, l, unit)
	BaseUnit  string
	CreatedAt time.Time
}

// A line item as it appears verbatim on a receipt
type RawItem struct {
	ID        int64
	ReceiptID int64
	// FK to product — nullable until the item is linked to a canonical product
	ProductID sql.NullInt64
	RawText   string
	// Quantity text as it appears on the receipt (e.g., "1 lb", "500g")
	RawQuantity sql.NullString
	// Parsed numeric quantity extracted from raw_quantity
	QuantityValue sql.NullFloat64
	// Normalized unit extracted from raw_quantity (e.g., g, lb, ml)
	QuantityUnit sql.NullString
	CreatedAt    time.Time
}

// A single receipt document belonging to a correspondent
type Receipt struct {
	ID int64
	// FK to correspondent — RESTRICT prevents deleting a correspondent with existing receipts
	CorrespondentID int64
	// Date-only: the purchase date printed on the receipt
	PurchasedAt time.Time
	// Ingestion source: paperless-ngx import or direct upload
	Source string
	// ID in the external source system (e.g., paperless-ngx document ID)
	ExternalDocID sql.NullString
	// Path or reference to the original receipt file
	RawFileRef sql.NullString
	CreatedAt  time.Time
}
