// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: price_record.sql

package db

import (
	"context"
	"database/sql"
)

const createPriceRecord = `-- name: CreatePriceRecord :one

INSERT INTO price_record (
    raw_item_id,
    total_price,
    unit_price,
    currency
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, raw_item_id, total_price, unit_price, currency, created_at
`

type CreatePriceRecordParams struct {
	RawItemID  int64
	TotalPrice float64
	UnitPrice  sql.NullFloat64
	Currency   string
}

// Price_record CRUD.
// A price observation tied to a raw item (1:1).
func (q *Queries) CreatePriceRecord(ctx context.Context, arg CreatePriceRecordParams) (PriceRecord, error) {
	row := q.db.QueryRowContext(ctx, createPriceRecord,
		arg.RawItemID,
		arg.TotalPrice,
		arg.UnitPrice,
		arg.Currency,
	)
	var i PriceRecord
	err := row.Scan(
		&i.ID,
		&i.RawItemID,
		&i.TotalPrice,
		&i.UnitPrice,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const deletePriceRecord = `-- name: DeletePriceRecord :exec
DELETE FROM price_record
WHERE id = $1
`

func (q *Queries) DeletePriceRecord(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePriceRecord, id)
	return err
}

const getPriceRecord = `-- name: GetPriceRecord :one
SELECT id, raw_item_id, total_price, unit_price, currency, created_at FROM price_record
WHERE id = $1
`

func (q *Queries) GetPriceRecord(ctx context.Context, id int64) (PriceRecord, error) {
	row := q.db.QueryRowContext(ctx, getPriceRecord, id)
	var i PriceRecord
	err := row.Scan(
		&i.ID,
		&i.RawItemID,
		&i.TotalPrice,
		&i.UnitPrice,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getPriceRecordByRawItem = `-- name: GetPriceRecordByRawItem :one
SELECT id, raw_item_id, total_price, unit_price, currency, created_at FROM price_record
WHERE raw_item_id = $1
`

func (q *Queries) GetPriceRecordByRawItem(ctx context.Context, rawItemID int64) (PriceRecord, error) {
	row := q.db.QueryRowContext(ctx, getPriceRecordByRawItem, rawItemID)
	var i PriceRecord
	err := row.Scan(
		&i.ID,
		&i.RawItemID,
		&i.TotalPrice,
		&i.UnitPrice,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const listPriceRecords = `-- name: ListPriceRecords :many
SELECT id, raw_item_id, total_price, unit_price, currency, created_at FROM price_record
ORDER BY id
`

func (q *Queries) ListPriceRecords(ctx context.Context) ([]PriceRecord, error) {
	rows, err := q.db.QueryContext(ctx, listPriceRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceRecord{}
	for rows.Next() {
		var i PriceRecord
		if err := rows.Scan(
			&i.ID,
			&i.RawItemID,
			&i.TotalPrice,
			&i.UnitPrice,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePriceRecord = `-- name: UpdatePriceRecord :one
UPDATE price_record
SET
    total_price = $2,
    unit_price = $3,
    currency = $4
WHERE id = $1
RETURNING id, raw_item_id, total_price, unit_price, currency, created_at
`

type UpdatePriceRecordParams struct {
	ID         int64
	TotalPrice float64
	UnitPrice  sql.NullFloat64
	Currency   string
}

func (q *Queries) UpdatePriceRecord(ctx context.Context, arg UpdatePriceRecordParams) (PriceRecord, error) {
	row := q.db.QueryRowContext(ctx, updatePriceRecord,
		arg.ID,
		arg.TotalPrice,
		arg.UnitPrice,
		arg.Currency,
	)
	var i PriceRecord
	err := row.Scan(
		&i.ID,
		&i.RawItemID,
		&i.TotalPrice,
		&i.UnitPrice,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}
