// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createProduct = `-- name: CreateProduct :one

INSERT INTO product (display_name, base_unit)
VALUES ($1, $2)
RETURNING id, display_name, base_unit, created_at
`

type CreateProductParams struct {
	DisplayName string
	BaseUnit    string
}

// Product CRUD.
// A canonical product identified after normalizing raw item text.
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct, arg.DisplayName, arg.BaseUnit)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.BaseUnit,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM product
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, display_name, base_unit, created_at FROM product
WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.BaseUnit,
		&i.CreatedAt,
	)
	return i, err
}

const getProductByName = `-- name: GetProductByName :one
SELECT id, display_name, base_unit, created_at FROM product
WHERE display_name = $1 LIMIT 1
`

func (q *Queries) GetProductByName(ctx context.Context, displayName string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByName, displayName)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.BaseUnit,
		&i.CreatedAt,
	)
	return i, err
}

const listLinkedProducts = `-- name: ListLinkedProducts :many
SELECT p.id, p.display_name, p.base_unit, p.created_at 
FROM product p
JOIN marketplace_link ml ON (ml.product_a_id = p.id OR ml.product_b_id = p.id)
WHERE (ml.product_a_id = $1 OR ml.product_b_id = $1) 
  AND p.id != $1
ORDER BY p.display_name
`

func (q *Queries) ListLinkedProducts(ctx context.Context, productAID int64) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listLinkedProducts, productAID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.BaseUnit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceHistoryByProduct = `-- name: ListPriceHistoryByProduct :many
SELECT 
    pr.id,
    pr.total_price,
    pr.unit_price,
    ri.raw_text,
    ri.raw_quantity,
    c.name AS correspondent_name,
    r.purchased_at
FROM price_record pr
JOIN raw_item ri ON pr.raw_item_id = ri.id
JOIN receipt r ON ri.receipt_id = r.id
JOIN correspondent c ON r.correspondent_id = c.id
WHERE ri.product_id = $1
ORDER BY r.purchased_at DESC
`

type ListPriceHistoryByProductRow struct {
	ID                int64
	TotalPrice        float64
	UnitPrice         sql.NullFloat64
	RawText           string
	RawQuantity       sql.NullString
	CorrespondentName string
	PurchasedAt       time.Time
}

func (q *Queries) ListPriceHistoryByProduct(ctx context.Context, productID sql.NullInt64) ([]ListPriceHistoryByProductRow, error) {
	rows, err := q.db.QueryContext(ctx, listPriceHistoryByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPriceHistoryByProductRow{}
	for rows.Next() {
		var i ListPriceHistoryByProductRow
		if err := rows.Scan(
			&i.ID,
			&i.TotalPrice,
			&i.UnitPrice,
			&i.RawText,
			&i.RawQuantity,
			&i.CorrespondentName,
			&i.PurchasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, display_name, base_unit, created_at FROM product
ORDER BY display_name
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.BaseUnit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE product
SET
    display_name = $2,
    base_unit = $3
WHERE id = $1
RETURNING id, display_name, base_unit, created_at
`

type UpdateProductParams struct {
	ID          int64
	DisplayName string
	BaseUnit    string
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct, arg.ID, arg.DisplayName, arg.BaseUnit)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.BaseUnit,
		&i.CreatedAt,
	)
	return i, err
}
