// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product.sql

package db

import (
	"context"
)

const createProduct = `-- name: CreateProduct :one

INSERT INTO product (display_name, base_unit)
VALUES ($1, $2)
RETURNING id, display_name, base_unit, created_at
`

type CreateProductParams struct {
	DisplayName string
	BaseUnit    string
}

// Product CRUD.
// A canonical product identified after normalizing raw item text.
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct, arg.DisplayName, arg.BaseUnit)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.BaseUnit,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM product
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, display_name, base_unit, created_at FROM product
WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.BaseUnit,
		&i.CreatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, display_name, base_unit, created_at FROM product
ORDER BY display_name
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.BaseUnit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE product
SET
    display_name = $2,
    base_unit = $3
WHERE id = $1
RETURNING id, display_name, base_unit, created_at
`

type UpdateProductParams struct {
	ID          int64
	DisplayName string
	BaseUnit    string
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct, arg.ID, arg.DisplayName, arg.BaseUnit)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.BaseUnit,
		&i.CreatedAt,
	)
	return i, err
}
