// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	// Correspondent CRUD.
	// A person or entity whose documents/receipts are tracked.
	CreateCorrespondent(ctx context.Context, name string) (Correspondent, error)
	// Marketplace_link CRUD.
	// A bidirectional pair link between two products across marketplaces.
	CreateMarketplaceLink(ctx context.Context, arg CreateMarketplaceLinkParams) (MarketplaceLink, error)
	// Price_record CRUD.
	// A price observation tied to a raw item (1:1).
	CreatePriceRecord(ctx context.Context, arg CreatePriceRecordParams) (PriceRecord, error)
	// Product CRUD.
	// A canonical product identified after normalizing raw item text.
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	// Raw_item CRUD.
	// A line item as it appears verbatim on a receipt, before normalization.
	CreateRawItem(ctx context.Context, arg CreateRawItemParams) (RawItem, error)
	// Receipt CRUD.
	// A single receipt document belonging to a correspondent.
	CreateReceipt(ctx context.Context, arg CreateReceiptParams) (Receipt, error)
	DeleteCorrespondent(ctx context.Context, id int64) error
	DeleteMarketplaceLink(ctx context.Context, id int64) error
	DeletePriceRecord(ctx context.Context, id int64) error
	DeleteProduct(ctx context.Context, id int64) error
	DeleteRawItem(ctx context.Context, id int64) error
	DeleteReceipt(ctx context.Context, id int64) error
	GetCorrespondent(ctx context.Context, id int64) (Correspondent, error)
	GetCorrespondentByName(ctx context.Context, name string) (Correspondent, error)
	GetMarketplaceLink(ctx context.Context, id int64) (MarketplaceLink, error)
	GetPriceRecord(ctx context.Context, id int64) (PriceRecord, error)
	GetPriceRecordByRawItem(ctx context.Context, rawItemID int64) (PriceRecord, error)
	GetProduct(ctx context.Context, id int64) (Product, error)
	GetProductByName(ctx context.Context, displayName string) (Product, error)
	GetRawItem(ctx context.Context, id int64) (RawItem, error)
	GetReceipt(ctx context.Context, id int64) (Receipt, error)
	ListCorrespondents(ctx context.Context) ([]Correspondent, error)
	ListLinkedProducts(ctx context.Context, productAID int64) ([]Product, error)
	ListMarketplaceLinks(ctx context.Context) ([]MarketplaceLink, error)
	ListMarketplaceLinksByProduct(ctx context.Context, productAID int64) ([]MarketplaceLink, error)
	ListPriceHistoryByProduct(ctx context.Context, productID sql.NullInt64) ([]ListPriceHistoryByProductRow, error)
	ListPriceRecords(ctx context.Context) ([]PriceRecord, error)
	ListProducts(ctx context.Context) ([]Product, error)
	ListRawItemsByReceipt(ctx context.Context, receiptID int64) ([]RawItem, error)
	ListReceipts(ctx context.Context) ([]Receipt, error)
	ListReceiptsByCorrespondent(ctx context.Context, correspondentID int64) ([]Receipt, error)
	UpdateCorrespondent(ctx context.Context, arg UpdateCorrespondentParams) (Correspondent, error)
	UpdatePriceRecord(ctx context.Context, arg UpdatePriceRecordParams) (PriceRecord, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateRawItem(ctx context.Context, arg UpdateRawItemParams) (RawItem, error)
	UpdateReceipt(ctx context.Context, arg UpdateReceiptParams) (Receipt, error)
}

var _ Querier = (*Queries)(nil)
