// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: raw_item.sql

package db

import (
	"context"
	"database/sql"
)

const createRawItem = `-- name: CreateRawItem :one

INSERT INTO raw_item (
    receipt_id,
    product_id,
    raw_text,
    raw_quantity,
    quantity_value,
    quantity_unit
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, receipt_id, product_id, raw_text, raw_quantity, quantity_value, quantity_unit, created_at
`

type CreateRawItemParams struct {
	ReceiptID     int64
	ProductID     sql.NullInt64
	RawText       string
	RawQuantity   sql.NullString
	QuantityValue sql.NullFloat64
	QuantityUnit  sql.NullString
}

// Raw_item CRUD.
// A line item as it appears verbatim on a receipt, before normalization.
func (q *Queries) CreateRawItem(ctx context.Context, arg CreateRawItemParams) (RawItem, error) {
	row := q.db.QueryRowContext(ctx, createRawItem,
		arg.ReceiptID,
		arg.ProductID,
		arg.RawText,
		arg.RawQuantity,
		arg.QuantityValue,
		arg.QuantityUnit,
	)
	var i RawItem
	err := row.Scan(
		&i.ID,
		&i.ReceiptID,
		&i.ProductID,
		&i.RawText,
		&i.RawQuantity,
		&i.QuantityValue,
		&i.QuantityUnit,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRawItem = `-- name: DeleteRawItem :exec
DELETE FROM raw_item
WHERE id = $1
`

func (q *Queries) DeleteRawItem(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRawItem, id)
	return err
}

const getRawItem = `-- name: GetRawItem :one
SELECT id, receipt_id, product_id, raw_text, raw_quantity, quantity_value, quantity_unit, created_at FROM raw_item
WHERE id = $1
`

func (q *Queries) GetRawItem(ctx context.Context, id int64) (RawItem, error) {
	row := q.db.QueryRowContext(ctx, getRawItem, id)
	var i RawItem
	err := row.Scan(
		&i.ID,
		&i.ReceiptID,
		&i.ProductID,
		&i.RawText,
		&i.RawQuantity,
		&i.QuantityValue,
		&i.QuantityUnit,
		&i.CreatedAt,
	)
	return i, err
}

const listRawItemsByReceipt = `-- name: ListRawItemsByReceipt :many
SELECT id, receipt_id, product_id, raw_text, raw_quantity, quantity_value, quantity_unit, created_at FROM raw_item
WHERE receipt_id = $1
ORDER BY id
`

func (q *Queries) ListRawItemsByReceipt(ctx context.Context, receiptID int64) ([]RawItem, error) {
	rows, err := q.db.QueryContext(ctx, listRawItemsByReceipt, receiptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RawItem{}
	for rows.Next() {
		var i RawItem
		if err := rows.Scan(
			&i.ID,
			&i.ReceiptID,
			&i.ProductID,
			&i.RawText,
			&i.RawQuantity,
			&i.QuantityValue,
			&i.QuantityUnit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRawItem = `-- name: UpdateRawItem :one
UPDATE raw_item
SET
    product_id = $2,
    raw_text = $3,
    raw_quantity = $4,
    quantity_value = $5,
    quantity_unit = $6
WHERE id = $1
RETURNING id, receipt_id, product_id, raw_text, raw_quantity, quantity_value, quantity_unit, created_at
`

type UpdateRawItemParams struct {
	ID            int64
	ProductID     sql.NullInt64
	RawText       string
	RawQuantity   sql.NullString
	QuantityValue sql.NullFloat64
	QuantityUnit  sql.NullString
}

func (q *Queries) UpdateRawItem(ctx context.Context, arg UpdateRawItemParams) (RawItem, error) {
	row := q.db.QueryRowContext(ctx, updateRawItem,
		arg.ID,
		arg.ProductID,
		arg.RawText,
		arg.RawQuantity,
		arg.QuantityValue,
		arg.QuantityUnit,
	)
	var i RawItem
	err := row.Scan(
		&i.ID,
		&i.ReceiptID,
		&i.ProductID,
		&i.RawText,
		&i.RawQuantity,
		&i.QuantityValue,
		&i.QuantityUnit,
		&i.CreatedAt,
	)
	return i, err
}
