// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: receipt.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createReceipt = `-- name: CreateReceipt :one

INSERT INTO receipt (
    correspondent_id,
    purchased_at,
    source,
    external_doc_id,
    raw_file_ref
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, correspondent_id, purchased_at, source, external_doc_id, raw_file_ref, created_at
`

type CreateReceiptParams struct {
	CorrespondentID int64
	PurchasedAt     time.Time
	Source          string
	ExternalDocID   sql.NullString
	RawFileRef      sql.NullString
}

// Receipt CRUD.
// A single receipt document belonging to a correspondent.
func (q *Queries) CreateReceipt(ctx context.Context, arg CreateReceiptParams) (Receipt, error) {
	row := q.db.QueryRowContext(ctx, createReceipt,
		arg.CorrespondentID,
		arg.PurchasedAt,
		arg.Source,
		arg.ExternalDocID,
		arg.RawFileRef,
	)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.CorrespondentID,
		&i.PurchasedAt,
		&i.Source,
		&i.ExternalDocID,
		&i.RawFileRef,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReceipt = `-- name: DeleteReceipt :exec
DELETE FROM receipt
WHERE id = $1
`

func (q *Queries) DeleteReceipt(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteReceipt, id)
	return err
}

const getReceipt = `-- name: GetReceipt :one
SELECT id, correspondent_id, purchased_at, source, external_doc_id, raw_file_ref, created_at FROM receipt
WHERE id = $1
`

func (q *Queries) GetReceipt(ctx context.Context, id int64) (Receipt, error) {
	row := q.db.QueryRowContext(ctx, getReceipt, id)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.CorrespondentID,
		&i.PurchasedAt,
		&i.Source,
		&i.ExternalDocID,
		&i.RawFileRef,
		&i.CreatedAt,
	)
	return i, err
}

const listReceipts = `-- name: ListReceipts :many
SELECT id, correspondent_id, purchased_at, source, external_doc_id, raw_file_ref, created_at FROM receipt
ORDER BY purchased_at DESC
`

func (q *Queries) ListReceipts(ctx context.Context) ([]Receipt, error) {
	rows, err := q.db.QueryContext(ctx, listReceipts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Receipt{}
	for rows.Next() {
		var i Receipt
		if err := rows.Scan(
			&i.ID,
			&i.CorrespondentID,
			&i.PurchasedAt,
			&i.Source,
			&i.ExternalDocID,
			&i.RawFileRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceiptsByCorrespondent = `-- name: ListReceiptsByCorrespondent :many
SELECT id, correspondent_id, purchased_at, source, external_doc_id, raw_file_ref, created_at FROM receipt
WHERE correspondent_id = $1
ORDER BY purchased_at DESC
`

func (q *Queries) ListReceiptsByCorrespondent(ctx context.Context, correspondentID int64) ([]Receipt, error) {
	rows, err := q.db.QueryContext(ctx, listReceiptsByCorrespondent, correspondentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Receipt{}
	for rows.Next() {
		var i Receipt
		if err := rows.Scan(
			&i.ID,
			&i.CorrespondentID,
			&i.PurchasedAt,
			&i.Source,
			&i.ExternalDocID,
			&i.RawFileRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReceipt = `-- name: UpdateReceipt :one
UPDATE receipt
SET
    correspondent_id = $2,
    purchased_at = $3,
    source = $4,
    external_doc_id = $5,
    raw_file_ref = $6
WHERE id = $1
RETURNING id, correspondent_id, purchased_at, source, external_doc_id, raw_file_ref, created_at
`

type UpdateReceiptParams struct {
	ID              int64
	CorrespondentID int64
	PurchasedAt     time.Time
	Source          string
	ExternalDocID   sql.NullString
	RawFileRef      sql.NullString
}

func (q *Queries) UpdateReceipt(ctx context.Context, arg UpdateReceiptParams) (Receipt, error) {
	row := q.db.QueryRowContext(ctx, updateReceipt,
		arg.ID,
		arg.CorrespondentID,
		arg.PurchasedAt,
		arg.Source,
		arg.ExternalDocID,
		arg.RawFileRef,
	)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.CorrespondentID,
		&i.PurchasedAt,
		&i.Source,
		&i.ExternalDocID,
		&i.RawFileRef,
		&i.CreatedAt,
	)
	return i, err
}
